config/routes.rb
Sportbook::Application.routes.draw do

  ####################
  # routs for db (using sportdb-admin rails engine)

  puts '[boot] routes.rb - before mount SportDbAdmin::Engine'
  mount SportDbAdmin::Engine, :at => '/db'
  puts '[boot] routes.rb - after mount SportDbAdmin::Engine'


  puts '[boot] routes.rb - before mount WorldDbAdmin::Engine'
  mount WorldDbAdmin::Engine, :at => '/worlddb'
  puts '[boot] routes.rb - after mount WorldDbAdmin::Engine'


  mount About::Server,     :at => '/sys'
  mount DbBrowser::Server, :at => '/browse'

  ## todo: add ActivityDb::Server too


  get 'signin',   :to => 'sessions#new'
  get 'signout',  :to => 'sessions#destroy'

  get 'about',    :to => 'pages#about'
  get 'home',     :to => 'pages#home'
  get 'style',    :to => 'pages#style'     # testpage for styles (css)

  get 'live',          :to => 'live#index'
  get 'live/:game_id', :to => 'live#show', :as => :live_game

  get 'time',             :to => 'time#index'
  get 'time2',            :to => 'time#index2'
  get 'time3',            :to => 'time#index3'   # old action timeline - obsolete remove/delete after cleanup!!
  get 'time4',            :to => 'time#index4'   # old action timeline - obsolete remove/delete after cleanup!!

  get 'ical/:play_id',   :to => 'ical#index'

  resource :session, :only => [:new, :create, :destroy]

  resource :password, :only => [:new, :create, :destroy]

  resources :profiles, :only => [:index, :show]

  resources :plays

  resources :pools do
    get 'add_player_to', :on => :member
    resources :players, :only => [:show, :edit]
  end

  #############
  # routes for admin

  get 'admin',  :to => 'admin/pools#index'
  
  namespace :admin do
    resources :pools

    # add plain text import forms for fixtures n quotes  
    resources :fixtures
    resources :quotes    
    
    get 'bonus',         :to => 'bonus#index'

    ## fix: post required?? double check!!
    get 'bonus/update',  :to => 'bonus#update'
  end

  ##############################
  # routes for admin via module (admin not in url -- todo/fix)
  
  scope :module => 'admin' do

    get 'update',         :to => 'update#index'
    put 'update/update',  :to => 'update#update'

    resources :jobs do
      get 'calc',            :on => :collection
      get 'debug_calc',      :on => :collection
      get 'export',          :on => :collection
      get 'keys',            :on => :collection
      get 'wipe_out_time',   :on => :collection
      get 'wipe_out',        :on => :collection
      get 'wipe_out_points', :on => :collection
    end

    resource :import, :only => [:create]

    resources :users
  end


  ##############################
  # routes for setup

  ## todo: move to admin - why? why not?

  get 'setup',  :to => 'setup/bonus_rounds#index'

  namespace :setup do
    resources :bonus_rounds
  end


  #######################
  # home route
  
  root :to => 'pages#home'
end

app/models/pool.rb
# == Schema Information
#
# Table name: pools
#
#  id           :integer         not null, primary key
#  event_id     :integer         not null
#  title        :string(255)     not null
#  user_id      :integer         not null
#  fix          :boolean         default(FALSE), not null
#  public       :boolean         default(TRUE), not null
#  locked       :boolean         default(FALSE), not null
#  welcome      :text
#  welcome_html :text
#  key          :string(255)
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#

module SportDb::Model

## NB: extend from sport.db-play gem


class Pool
  
  
  after_create :log_action_create
  
  before_save :on_before_save
  
  def on_before_save
    if welcome.blank?
      self.welcome_html = ''
    else
      self.welcome_html = markdown_to_html( welcome )
    end
  end
  
  def welcome_header_html
    return '' if welcome_html.blank?
    
    ## return everything up to (optional) <!-- more
    pos = welcome_html.index('<!-- more')
    if pos.nil?
      welcome_html
    else
      welcome_html[0...pos]  # NB: three point range (that is, ... => exlude the end value)
    end
  end
  
  ## todo/fix: can we use log_action_create! in filter??
  def log_action_create
    a = Action.new

    a.user_id = user_id
    a.pool_id = id
    a.tmpl    = 'pool-create'
    a.text    = "#{user.name} managt Wettpool >#{full_title}<. Mach mit! Tipp mit!"

    a.save!
  end
    
##  def full_title
##    "#{title} #{event.title}#{fix? ? ' Fix' : ''}"
##  end
  
  def fix?
    fix == true
  end
  
  def flex?
    fix != true
  end
  
  
end # class Pool

end  # module SportDb::Model

Pool = SportDb::Model::Pool

app/controllers/admin/pools_controller.rb
class Admin::PoolsController < Admin::BaseController

  # GET /pools
  def index
    @pools = Pool.all
  end
  
  # GET /pools/new
  def new
    @pool = Pool.new
  end

  # POST /pools
  def create
    @pool = Pool.new(params[:pool])
    @pool.user = current_user()

    if @pool.save
      redirect_to admin_pools_path(), :notice => 'Pool erfolgreich gespeichert.' 
    else
      render :action => 'new'
    end
  end
  
  # GET /pools/1/edit
  def edit
    @pool = Pool.find(params[:id])
  end

  # PUT /pools/1
  def update
    @pool = Pool.find(params[:id])

    if @pool.update_attributes(params[:pool])
      redirect_to admin_pools_path(), :notice => 'Pool erfolgreich gespeichert.'
    else
      render :action => 'edit'
    end
  end
  


end # class PoolsController

app/controllers/pools_controller.rb
class PoolsController < ApplicationController

  # GET /pools
  def index
    @pools = Pool.all
    
    # find next upcoming games
    
    limit = params[:limit] || '12'
    
    @upcoming_games = Game.where( 'play_at > ?', Time.now ).order( 'play_at').limit(limit)
    @past_games     = Game.where( 'play_at < ?', Time.now ).order( 'play_at desc').limit(limit)
  end

  # GET /pools/1
  def show
    @pool = Pool.find(params[:id])
  end
  
  def add_player_to
    @pool = Pool.find(params[:id])
    @pool.players << current_user()
    
    ## todo: how to get play_id??  (form pool.players << current_user)
    ##  use edit_play() route (otherwise flash message get lost (two redirects))
    
    flash[ :success ] = "Willkommen im Wettpool. Los geht's."
    redirect_to edit_pool_player_path( @pool, current_user() )
  end
  
end # class PoolsController

app/views/pools/_games_past.html.erb
<h3><%= t(:past_games) %></h3>

<!-- use partial for upcoming and past games?? -->
<table class='live'>
<% last_play_at = Time.local( 1999, 1, 1 )
   games.each do |game| %>
   
  <% unless last_play_at.year   == game.play_at.year  &&
            last_play_at.month  == game.play_at.month &&
            last_play_at.day    == game.play_at.day %>
        
    <tr style='background-color: silver;'>
      <td colspan='10'><%= game.play_at.strftime('%A, %d. %B %Y') %></td>
    </tr> 
        
  <% end %>
      
 <tr style='vertical-align: middle;'>
  <td>
    <%= game.play_at.strftime('%H:%M') %>
  </td>
  <td style='text-align: right;'>
    <span class='<%= game.team1_style_class %>'>
      <%= link_to game.team1.title, live_game_path( game.id ) %>
    </span>
  </td>
  <td>
    <%= logo_for_team( game.team1 ) %>
  </td>
  <td><%= game.score_str %></td>
  <td>
    <%= logo_for_team( game.team2 ) %>
  </td>
  <td>
    <span class='<%= game.team2_style_class %>'>
      <%= link_to game.team2.title, live_game_path( game.id ) %>
    </span>
  </td>
  <td>
    (<%= game.round.event.title %> / <%= game.round.title %>)
  </td>
  
    <% tips = game.tips.where( :user_id => current_user_id() ).all %>
  
    <!-- <%= tips.count %> Tipps -->
  
    <% tips.each do |tip| %>
     <td>
      <% if tip.toto12x %>
       <span class='toto12x'><%= tip.toto12x %></span>
      <% end %>
     </td>
     <td style='text-align: center;'>
      <span class='<%= tip.bingo_style_class %>'>
        <%= tip.score_str %>
      </span>
     </td>
     <% end %><!-- each tip -->
  </td>
 </tr> 
<% last_play_at = game.play_at
   end %><!-- each game -->
</table>

<% if games.count > 0 %>
<p><%= link_to "#{t(:more_games)} »", live_path(:limit => 10, :tips=>true, :past=>true) %>
</p>
<% else %>
<p>Noch keine Spiele bekannt.</p>
<% end %>

app/views/pools/_games_upcoming.html.erb
<h3><%= t(:upcoming_games)%></h3>

<table>
<% last_play_at = Time.local( 1999, 1, 1 )
   games.each do |game| %>
 
  <% unless last_play_at.year   == game.play_at.year  &&
            last_play_at.month  == game.play_at.month &&
            last_play_at.day    == game.play_at.day %>
        
    <tr style='background-color: silver;'>
      <td colspan='10'><%= game.play_at.strftime('%A, %d. %B %Y') %></td>
    </tr> 
        
  <% end %>
 
 
 <tr style='vertical-align: middle;'>
  <td>
    <%= game.play_at.strftime('%H:%M') %>
  </td>
  <td style='text-align: right;'>
    <%= link_to game.team1.title, live_game_path( game.id ) %>
    <%= "(#{game.team1.title2})" if game.team1.title2.present? %>
  </td>
  <td>
    <%= logo_for_team( game.team1 ) %>
  </td>
  <td> -  <%#= game.score_str %>
  </td>
  <td>
    <%= logo_for_team( game.team2 ) %>
  </td>
  <td>
    <%= link_to game.team2.title, live_game_path( game.id ) %>
    <%= "(#{game.team2.title2})" if game.team2.title2.present? %>
  </td>
  <td>
    (<%= game.round.event.title %> / <%= game.round.title %>)
  </td>
  
  
    <% tips = game.tips.where( :user_id => current_user_id() ).all %>
  
    <!-- <%= tips.count %> Tipps -->
  
    <% tips.each do |tip| %>
     <td>
      <% if tip.toto12x %>
       <span class='toto12x'><%= tip.toto12x %></span>
      <% end %>
     </td>
     <td style='text-align: center;'>
      <span class='<%= tip.bingo_style_class %>'>
        <%= tip.score_str %>
      </span>
     </td>
     <td>
        <%= link_to t(:edit), edit_pool_player_path( tip.pool_id, tip.user.id), :class => 'btn' %>
      </td>
     <% end %><!-- each tip -->
  
    <td>
       <%= render_game_quotes( game ) %>
    </td>
  
 </tr> 
<% last_play_at = game.play_at
   end %><!-- each game -->
</table>


<% if games.count > 0 %>
<p><%= link_to "#{t(:more_games)} »", live_path(:limit => 10, :tips=>true) %>
</p>
<% else %>
<p>Noch keine Spiele bekannt.
</p>
<% end %>

app/views/pools/index.html.erb
<% content_for :breadcrumb do %>
  <%= link_to 'Wettpools', pools_path() %>
<% end %>



<%= render partial: 'games_upcoming', locals: { games: @upcoming_games } %>

<h3>Wettpools</h3>

<ul>
<% @pools.each do |pool| %>
  <li><%= link_to pool.full_title, pool_path(pool) %>
    (
      Manager <%= pool.user.name %>,
      <%= link_to "#{pool.players.size} Mitspieler", plays_path( :pool_id => pool.id ) %>
    )
    <br>
    <div class='pool welcome-header'><%= raw( pool.welcome_header_html ) %></div>
  </li>
<% end %>
</ul>

<%= render partial: 'games_past', locals: { games: @past_games } %>

app/views/pools/show.html.erb
<% title( @pool.full_title ) %>

<% content_for :breadcrumb do %>
 <%= link_to 'Wettpools', pools_path() %> ›
 <%= link_to @pool.full_title, pool_path( @pool) %>
<% end %>


<!-- todo:
   use current_play = nil or obj  instead of machmit  => lets us use play route for edit!!
  -->

<% machmit = (@pool.players.include?( current_user ) == false) %>
  
<table width='100%' cellspacing=0>
  <tr>
    <!-- left -->
    <td>
       <h1><%= @pool.full_title %></h1>
    </td>
    <!-- right -->
    <td style='text-align: right;'>
<% if machmit %>
  <%= link_to t(:join_pool), add_player_to_pool_path( @pool ), :class => 'btn-primary' %>
<% else %>
  <%= link_to t(:edit_bets), edit_pool_player_path( @pool, current_user() ), :class => 'btn-primary' %>
<% end %>
    </td>
  </tr>
</table>


<p>
  Manager <%= @pool.user.name %>,
  <%= link_to "#{@pool.players.size} Mitspieler (Alle Tipps)", plays_path( :pool_id => @pool.id ) %>
</p>

<p><%= raw( @pool.welcome_html ) %></p>




<table width='100%' cellspacing=0>

<% @pool.bonus_rounds.reorder('pos desc').each do |round| %>

<tr>
  <td colspan='2' style='background-color: lightgrey;'><%= round.title %></td>
</tr>

  <tr>
    <!-- left -->
    <td>
  <!-- runden ergebnis -->

    <table>
  <%
     last_pts=-1
     BonusPoint.where( :pool_id => @pool.id, :round_id => round.id ).order( 'round_pts desc').each do |ranking|
   %>
      
     <!-- don't add css class (ranking, that is, bigger) if all scores are 0 -->
     <% if ranking.round_pos == 1 && ranking.round_pts == 0 %>
       <tr><!-- everyone is a winner #1 - all points 0 -->
     <% else %>
       <tr class='<%= "ranking#{ranking.round_pos}" %>'>
     <% end %>
        <td>
          <!-- add ranking e.g. 1., 2. etc.; check for same scores (don't display if ex equo for followers)-->
          <%#= "#{ranking.round_pos}." if ranking.round_pts != last_pts %>
        </td>
        <td>
          <span class='<%= hl_style_for_user(ranking.user) %>'>
            <%= link_to ranking.user.name, pool_player_path( @pool.id, ranking.user ) %>
          </span>
        </td>
        <td><%= ranking.round_pts %> Punkte</td>
      </tr>
  <%
    last_pts = ranking.round_pts
    end
   %>
     </table>
     
    </td>
    <!-- right -->
    <td>
  <!-- gesamt ergebnis -->

    <table>
  <%  last_pts=-1
      BonusPoint.where( :pool_id => @pool.id, :round_id => round.id ).order( 'total_pts desc').each do |ranking|
   %>
     <!-- don't add css class (ranking, that is, bigger) if all scores are 0 -->
     <% if ranking.total_pos == 1 && ranking.total_pts == 0 %>
       <tr><!-- everyone is a winner #1 - all points 0 -->
     <% else %>
       <tr class='<%= "ranking#{ranking.total_pos}" %>'>
     <% end %>
        <td>
          <!-- add ranking e.g. 1., 2. etc.; check for same scores (don't display if ex equo for followers)-->
          <%#= "#{ranking.total_pos}." if ranking.total_pts != last_pts %>
        </td>
        <td>
          <!-- add diff pos? -->
        </td>
        <td>
          <span class='<%= hl_style_for_user(ranking.user) %>'>
            <%= link_to ranking.user.name, pool_player_path( @pool.id, ranking.user ) %>
          </span>
        </td>
        <td><%= ranking.total_pts %> Punkte</td>
      </tr>
  <%
      last_pts = ranking.total_pts
      end
  %>
     </table>
      
    </td>
  </tr>

<% end %><!-- each rounds -->
</table>

<!-------
  ----->

<table width='100%' cellspacing=0>

<!-- todo/fix: use better lookup for rounds (e.g. use round.over? round.past? or similar??) -->
<!-- note: need to use reorder (to override default ordering!) -->
<%
   rounds = @pool.flex? ? @pool.event.flex_rounds.reorder('pos desc') : @pool.event.fix_rounds.reorder('pos desc')
   rounds.each do |round|
 %>

<tr>
  <td colspan='2' style='background-color: lightgrey;'><%= round.title %></td>
</tr>

  <tr>
    <!-- left -->
    <td>
  <!-- runden ergebnis -->

    <table>
  <%
     last_pts=-1
     Point.where( :pool_id => @pool.id, :round_id => round.id ).order( 'round_pts desc').each do |ranking|
   %>
      
     <!-- don't add css class (ranking, that is, bigger) if all scores are 0 -->
     <% if ranking.round_pos == 1 && ranking.round_pts == 0 %>
       <tr><!-- everyone is a winner #1 - all points 0 -->
     <% else %>
       <tr class='<%= "ranking#{ranking.round_pos}" %>'>
     <% end %>
        <td>
          <!-- add ranking e.g. 1., 2. etc.; check for same scores (don't display if ex equo for followers)-->
          <%= "#{ranking.round_pos}." if ranking.round_pts != last_pts %>
        </td>
        <td>
          <span class='<%= hl_style_for_user(ranking.user) %>'>
            <%= link_to ranking.user.name, pool_player_path( @pool.id, ranking.user ) %>
          </span>
        </td>
        <td><%= ranking.round_pts %> Punkte</td>
      </tr>
  <%
    last_pts = ranking.round_pts
    end
   %>
     </table>
     
    </td>
    <!-- right -->
    <td>
  <!-- gesamt ergebnis -->

    <table>
  <%  last_pts=-1
      Point.where( :pool_id => @pool.id, :round_id => round.id ).order( 'total_pts desc').each do |ranking|
   %>
     <!-- don't add css class (ranking, that is, bigger) if all scores are 0 -->
     <% if ranking.total_pos == 1 && ranking.total_pts == 0 %>
       <tr><!-- everyone is a winner #1 - all points 0 -->
     <% else %>
       <tr class='<%= "ranking#{ranking.total_pos}" %>'>
     <% end %>
        <td>
          <!-- add ranking e.g. 1., 2. etc.; check for same scores (don't display if ex equo for followers)-->
          <%= "#{ranking.total_pos}." if ranking.total_pts != last_pts %>
        </td>
        <td>
          <span class='<%= ranking.diff_total_pos_style_class %>'>
            <%= ranking.diff_total_pos_str %>
          </span>
        </td>
        <td>
          <span class='<%= hl_style_for_user(ranking.user) %>'>
            <%= link_to ranking.user.name, pool_player_path( @pool.id, ranking.user ) %>
          </span>
        </td>
        <td><%= ranking.total_pts %> Punkte</td>
      </tr>
  <%
      last_pts = ranking.total_pts
      end
  %>
     </table>
      
    </td>
  </tr>

<% end %><!-- each rounds -->
</table>