config/routes.rb
Sportbook::Application.routes.draw do

  ####################
  # routs for db (using sportdb-admin rails engine)

  puts '[boot] routes.rb - before mount SportDbAdmin::Engine'
  mount SportDbAdmin::Engine, :at => '/db'
  puts '[boot] routes.rb - after mount SportDbAdmin::Engine'


  puts '[boot] routes.rb - before mount WorldDbAdmin::Engine'
  mount WorldDbAdmin::Engine, :at => '/worlddb'
  puts '[boot] routes.rb - after mount WorldDbAdmin::Engine'


  mount About::Server,     :at => '/sys'
  mount DbBrowser::Server, :at => '/browse'

  ## todo: add ActivityDb::Server too


  get 'signin',   :to => 'sessions#new'
  get 'signout',  :to => 'sessions#destroy'

  get 'about',    :to => 'pages#about'
  get 'home',     :to => 'pages#home'
  get 'style',    :to => 'pages#style'     # testpage for styles (css)

  get 'live',          :to => 'live#index'
  get 'live/:game_id', :to => 'live#show', :as => :live_game

  get 'time',             :to => 'time#index'
  get 'time2',            :to => 'time#index2'
  get 'time3',            :to => 'time#index3'   # old action timeline - obsolete remove/delete after cleanup!!
  get 'time4',            :to => 'time#index4'   # old action timeline - obsolete remove/delete after cleanup!!

  get 'ical/:play_id',   :to => 'ical#index'

  resource :session, :only => [:new, :create, :destroy]

  resource :password, :only => [:new, :create, :destroy]

  resources :profiles, :only => [:index, :show]

  resources :plays

  resources :pools do
    get 'add_player_to', :on => :member
    resources :players, :only => [:show, :edit]
  end

  #############
  # routes for admin

  get 'admin',  :to => 'admin/pools#index'
  
  namespace :admin do
    resources :pools

    # add plain text import forms for fixtures n quotes  
    resources :fixtures
    resources :quotes    
    
    get 'bonus',         :to => 'bonus#index'

    ## fix: post required?? double check!!
    get 'bonus/update',  :to => 'bonus#update'
  end

  ##############################
  # routes for admin via module (admin not in url -- todo/fix)
  
  scope :module => 'admin' do

    get 'update',         :to => 'update#index'
    put 'update/update',  :to => 'update#update'

    resources :jobs do
      get 'calc',            :on => :collection
      get 'debug_calc',      :on => :collection
      get 'export',          :on => :collection
      get 'keys',            :on => :collection
      get 'wipe_out_time',   :on => :collection
      get 'wipe_out',        :on => :collection
      get 'wipe_out_points', :on => :collection
    end

    resource :import, :only => [:create]

    resources :users
  end


  ##############################
  # routes for setup

  ## todo: move to admin - why? why not?

  get 'setup',  :to => 'setup/bonus_rounds#index'

  namespace :setup do
    resources :bonus_rounds
  end


  #######################
  # home route
  
  root :to => 'pages#home'
end

app/models/play.rb
# == Schema Information
#
# Table name: plays
#
#  id         :integer         not null, primary key
#  user_id    :integer         not null
#  pool_id    :integer         not null
#  team1_id   :integer
#  team2_id   :integer
#  team3_id   :integer
#  total_pts  :integer         default(0), not null
#  total_pos  :integer         default(0), not null
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

module SportDb::Model
  
## NB: extend from sport.db-play gem


class Play
  
  
  after_create :log_action_create
  after_update :log_action_update

  def log_action_create
    a = Action.new

    a.user_id = user_id
    a.pool_id = pool_id
    a.tmpl    = 'play-create'
    a.text    = "#{user.name} tippt mit im Wettpool >#{pool.full_title}<. Willkommen!"

    a.save!
  end
    
  def log_action_update
    
    # only log if user action (not background job e.g. for update on total_pts)
    return if job_running?
    
    # only log if we got at least one team
    return if team1_id.blank? && team2_id.blank? && team3_id.blank?
    
    a = Action.new

    a.user_id = user_id
    a.pool_id = pool_id
    a.tmpl    = 'play-update'
    
    buf = ""
    buf << "#{user.name} tippt "
    buf << "1. Platz => #{team1.title} " if team1.present?
    buf << "2. Platz => #{team2.title} " if team2.present?
    buf << "3. Platz => #{team3.title} " if team3.present?
    buf << " im Wettpool >#{pool.full_title}<."
    
    a.text = buf
    a.save!
  end
    
end   # class Play

end # module SportDb::Model

Play = SportDb::Model::Play

app/controllers/plays_controller.rb
# encoding: utf-8

class PlaysController < ApplicationController
  
  # GET /plays?pool_id=:id
  def index
    @pool   = Pool.find( params[:pool_id] )
    @users  = @pool.players.order(:name)

    @show_pts  = param_show_pts?
    @show_tips = param_show_tips?
    
    @rounds = @pool.flex? ? @pool.event.flex_rounds.all : @pool.event.fix_rounds.all
  end

  # GET /plays/:id
  def show
    @play = Play.find( params[:id] )
    @pool = @play.pool
    @user = @play.user
    
    @rounds = @pool.flex? ? @pool.event.flex_rounds.all : @pool.event.fix_rounds.all
  end

  # GET /plays/:id/edit
  def edit
    @play = Play.find( params[:id] )
    @pool = @play.pool
    @user = @play.user

    # show odds by default
    @show_odds  = param_show_odds?


    pool_rounds = @pool.flex? ? @pool.event.flex_rounds.all : @pool.event.fix_rounds.all
    pool_rounds.each do |round|
      round.games.each do |game|
        # make sure all games exists as tips
        tips = @user.tips.where( :pool_id => @pool.id, :game_id => game.id ).all
        pp tips
        if tips.empty?
          if game.calc?
            tip = CalcTip.create!( :user => @user, :pool => @pool, :game => game )
            puts "*** adding calc tip #{tip.id} for calc game #{game.id}"
          else
            tip = Tip.create!( :user => @user, :pool => @pool, :game => game )
            puts "*** adding tip #{tip.id} for game #{game.id}"
          end
        else
          puts "*** found tip for game #{game.id}"
        end
      end # each game
    end # each round
    
  end # method edit

  # PUT /plays/:id
  def update

    ## fix/todo: check for errors on save (e.g. game over? no more changes allowed!)

    play = Play.find( params[:id] )

    # only update if has changes (to avoid duplicate/false action item in news feed)
   
    team1_id = params[:play][:team1_id].blank? ? nil : params[:play][:team1_id].to_i
    team2_id = params[:play][:team2_id].blank? ? nil : params[:play][:team2_id].to_i
    team3_id = params[:play][:team3_id].blank? ? nil : params[:play][:team3_id].to_i
   
    if( play.team1_id != team1_id || play.team2_id != team2_id || play.team3_id != team3_id )
      
      logger.info "*** updating play (#{team1_id},#{team2_id},#{team3_id})"
      
      play.team1_id = team1_id
      play.team2_id = team2_id
      play.team3_id = team3_id
      play.save!
    else
      logger.info "*** skip updating play - no changes"
    end  
      

   # check for case w/ no tips
   if params[:play][:tips]
    params[:play][:tips].each do |tip_key,tip_hash|
      tip = Tip.find( tip_key )
      
      # only update if has changes (to avoid duplicate/false action item in news feed)
      
      score1 = tip_hash[:score1].blank? ? nil : tip_hash[:score1].to_i
      score2 = tip_hash[:score2].blank? ? nil : tip_hash[:score2].to_i
      score3 = tip_hash[:score3].blank? ? nil : tip_hash[:score3].to_i
      score4 = tip_hash[:score4].blank? ? nil : tip_hash[:score4].to_i
      score5 = tip_hash[:score5].blank? ? nil : tip_hash[:score5].to_i
      score6 = tip_hash[:score6].blank? ? nil : tip_hash[:score6].to_i
      
      calc_team1_id = tip_hash[:calc_team1_id].blank? ? nil : tip_hash[:calc_team1_id].to_i
      calc_team2_id = tip_hash[:calc_team2_id].blank? ? nil : tip_hash[:calc_team2_id].to_i
            
      if (tip.score1 != score1 || tip.score2 != score2 ||
          tip.score3 != score3 || tip.score4 != score4 ||
          tip.score5 != score5 || tip.score6 != score6 ||
          (tip.calc? && tip.calc_team1_id != calc_team1_id) ||
          (tip.calc? && tip.calc_team2_id != calc_team2_id))

        logger.info "*** updating tip #{tip_key} (#{score1}:#{score2})"

        tip.score1 = score1
        tip.score2 = score2
        tip.score3 = score3
        tip.score4 = score4
        tip.score5 = score5
        tip.score6 = score6
        
        if tip.calc?
          tip.calc_team1_id = calc_team1_id
          tip.calc_team2_id = calc_team2_id
        end
        
        tip.save!
      else
        logger.info "*** skip updating tip #{tip_key} - no changes"
      end
    end
   end

    flash[:success] = 'Tipps erfolgreich gespeichert.'
        
    redirect_to edit_play_path( play )
  end
  
  private
  def param_show_pts?
    # do NOT show points by default
    params[:pts].present? && ['1','t','true','yes', 'on'].include?( params[:pts])
  end
  
  def param_show_tips?
    # show tips by default
    params[:tips].nil? || (params[:tips].present? && ['1','t','true','yes', 'on'].include?( params[:tips]))
  end

  def param_show_odds?
    # show odds (quotes) by default
    params[:odds].nil? || (params[:odds].present? && ['1','t','true','yes', 'on'].include?( params[:odds]))
  end  

end  # class PlaysController

app/views/plays/_games_by_group.html.erb
<!-- NB: only use for fix pools -->

<!-- requires: groups, user, pool, f (form) -->


<!-- table columns:
        1    => toto12x
        2    => bingo
        3    => team1
        4    => tip 
        5    => result
        6    => team2
        7    => round title
        8    => date
        
        9    => table/standing (n rowspan)
  -->

<% groups.each do |group| %>
<table class='play keep-together' cellspacing=0>
<tr class='game-group'>
  <td colspan='3'></td>
  <td colspan='6' class='game-group-title'><%= group.title %></td>
</tr>
  
<tr>
  <td colspan='9'>

<table>
 <tr>
  <td><!-- begin 1st column -->
<table class='standing'>
    <tr id='standing-g<%= group.id %>'>
       <td>Tabelle</td>
       <td>Spiele</td>
       <td>S</td>
       <td>U</td>
       <td>N</td>
       <td>Tore</td>
       <td>+/-</td>
       <td>Punkte</td>
     </tr>
    <% group.teams.each do |team| %>
        <tr id='standing-t<%= team.id %>'>
          <td><%= team.title %></td>
          <td class='right'>0</td>
          <td class='right'>0</td>
          <td class='right'>0</td>
          <td class='right'>0</td>
          <td class='right'>0 - 0</td>
          <td class='right'>0</td>
          <td class='right'>0</td>
        </tr>
    <% end %>
</table>
</td><!-- end 1st column -->

<% if show_odds %>
<td><!-- begin 2nd column -->
<table class='odds'>
 <tr>
<% Service.all.each do |srv| %>
   <td>
    <%= srv.title %><br>
  <% srv.group_quotes.where( :group_id => group.id ).each do |quote| %>
     <%= quote.team.tag %> <%= fmt_quote( quote.odds ) %><br>
  <% end %><!-- each qoute -->
  </td>
<% end %><!-- each service -->
</tr>
</table>
</td><!-- end 2nd column -->
<% end %><!-- show odds? -->
</tr>
</table>
  
  </td>
</tr>
  
  
  <% group.games.each do |game| %>
  
    <%= render :partial => 'tr_game_with_tip',
               :locals  => { :game => game,
                             :tip  => Tip.find_by_user_and_pool_and_game( user, pool, game ),
                             :show_round => true,
                             :show_group => false,
                             :show_odds  => show_odds,
                             :f => f,
                             :tabindex => (tabindex+=10) }  %>

  <% end %><!-- game -->
</table>
<% end %><!-- groups -->

app/views/plays/_games_by_round.html.erb
<!-- requires: rounds, user, pool, f (form) -->

<!-- table columns:
        1    => toto12x
        2    => bingo
        3    => team1
        4    => tip 
        5    => result
        6    => team2
        7    => group
        8    => date
  -->



<% rounds.each do |round| %>

<a name="<%= round.id %>"></a>
<table class='play keep-together' cellspacing=0>
<tr class='game-round'>
  <td colspan='3'></td>
  <td colspan='6' class='game-round-title'><%= round.title %> / <%= round.title2 %></td>
</tr>
  <% if round.games.count == 0 %>
     <tr>
       <td colspan='2'></td>
       <td colspan='6' class='game-no-fixtures'>Spielaufstellungen noch nicht bekannt.</td>
     </tr>
  <% else %>
  <% round.games.each do |game| %>

    <%= render :partial => 'tr_game_with_tip',
               :locals  => { :game => game,
                             :tip  => Tip.find_by_user_and_pool_and_game( user, pool, game ),
                             :show_round => false,
                             :show_group => true,
                             :show_odds  => show_odds,
                             :f => f,
                             :tabindex => (tabindex+=10) }  %>

  <% end %><!-- game -->
 <% end %> <!-- if round.games.count == 0 -->
</table>
<% end %><!-- rounds -->

app/views/plays/_tr_game_with_tip.html.erb
<!-- requires: game, tip, tabindex, f (form) -->

<!-- options:
      - show_group
      - show_round  -->


<tr id='game<%= game.id %>'>

  <% if tip.present? %>
    <% if game.over? || tip.locked? %>
      <!-- fix/todo: add a flag/icon for locked? game over? -->
      <%= render_tip_toto12x( tip )  %>
      <%= render_tip_bingo( tip )  %>
      <%= render_game_team1( game ) %>
      <%= render_tip_score( tip )  %>
      <%= render_game_score( game ) %>
    <% else %>
      <td><!-- no tip.toto12x yet --></td>
      <td><!-- no tip.bingo yet --></td>
      <%= render_game_team1( game ) %>
      <%= render_tip_score_input_for_form( tip, f, :tabindex => tabindex ) %>
      <td><!-- no game.score yet --></td>
    <% end %>
    <%= render_game_team2( game ) %>
  <% else %> <!-- no tip present -->
    <td><!-- no tip.toto12x yet --></td>
    <td><!-- no tip.bingo yet --></td>
    <%= render_game_team1( game ) %>
    <td class='tip-score'>♦<!-- fehler: tip datensatz fehlt! --></td>
    <%= render_game_score( game ) %>
    <%= render_game_team2( game ) %>
  <% end %>


  <td>
  <%= render_game_quotes( game ) if show_odds %>
  </td>

  
  <td class='game-group game-round'>
    <% if show_group %>
      <%= "(#{game.group.title})" if game.group %>
    <% elsif show_round %>
      <%= "(#{game.round.title})" %>
    <% end %>
  </td>

  <%= render_game_date( game ) %>

</tr>

app/views/plays/edit.html.erb
<% title( @user.name, @pool.full_title ) %>

<% content_for :breadcrumb do %>
 <%= link_to 'Wettpools', pools_path() %> ›
 <%= link_to @pool.full_title, pool_path(@pool) %> ›
 <%= link_to @user.name, play_path( @play ) %> ›
 <%= link_to 'Edit', edit_play_path( @play ) %>
<% end %>

<p class='view'>
  View: <%= link_to 'Tipps', edit_play_path( @play, :odds => 'f' ) %>
          ⋅
        <%= link_to 'Tipps+Quoten', edit_play_path( @play, :odds => 't' ) %>
</p>


<style>
 /* styling for table_expander */

  tr.bonus-round {
    background-color: silver;
  }

  tr.game-round,
  tr.bonus-round {
    cursor: pointer;
  }
  
  tr.game-round.expander-hide,
  tr.bonus-round.expander-hide {
   background-color: navy;
   color: white;
  }
  tr.game-round.expander-hide td,
  tr.bonus-round.expander-hide td {
   background-color: navy;
   color: white;
  }

  
  tr.game-round.expander-hide td.first,
  tr.game-round.expander-show td.first,
  tr.bonus-round.expander-hide td.first,
  tr.bonus-round.expander-show td.first {
    padding-left: 17px;   /* 2+15 */
    background-repeat: no-repeat;
    background-position: left center;
  }
      
  tr.game-round.expander-hide td.first,
  tr.bonus-round.expander-hide td.first {
    background-image: url(<%= asset_path('down-arrow.png') %>);
  }

  tr.game-round.expander-show td.first,
  tr.bonus-round.expander-show td.first {
    background-image: url(<%= asset_path('right-arrow.png') %>);
  }
 
 
</style>



<script>
  // add hotkey handler for quick tip autofill

 // function testTimer()
 // {
 //   $( '#debug').append( '<p>' + new Date().toString() + '</p>' );
 // }

 $(document).ready( function() {  
  
  table_expander( 'table.play', 'game-round' );
  table_expander( 'table.bonus', 'bonus-round' );
  
  recalcPlayTips();
  
  $(document).on( 'keydown', function( event ) {
    if( (event.ctrlKey && event.which == 81) || (event.which == 81) )  // ASCII 81 = Q (Quicktipp)
    {
       event.preventDefault();
       autofillPlayTips();
       recalcPlayTips();
       return false;  // todo: check if return false is  needed?
     }
     else if( (event.ctrlKey && event.which == 67) || (event.which == 67) )  // ASCII 67 = C (Clean/Clear)
     {
       event.preventDefault();
       clearPlayTips();
       recalcPlayTips();
       return false;  // todo: check if return false is  needed?      
     }
     else if( (event.ctrlKey && event.which == 82) || (event.which == 82) )  // ASCII 82 = R (Refresh/Recalcuate)
     {
       event.preventDefault();
       recalcPlayTips();
       return false;  // todo: check if return false is  needed?
     }
  });
  
  // quick and dirty hack
  //  do a recalc every ~2 seconds (e.g. 1500 ms)
  
  var recalcTimer = setInterval( recalcPlayTips, 1500 );
  
});
</script>


<table width='100%' cellspacing=0>
  <tr>
    <!-- left -->
    <td>
       <h1><%= @user.name %> - <%=  @pool.full_title %> Tipps</h1>
    </td>
    <!-- right -->
    <td style='text-align: right;'>
        <%= link_to t(:quickbets), '#', :class => 'btn', :onclick => 'autofillPlayTips();' %>
    </td>
  </tr>
</table>




 <!-- NB: namespaced model gets converted to sportsdb_models_play but only want user in params, thus, use as: option -->
<%= form_for @play, :as => :play, :url => play_path( @play ), :html => { :method => 'put' } do |f| %>  


<!-- todo/fix:

   break into two partials
   - _edit_flex.html.erb
   - _edit_fix.html.erb
  -->


<% if @pool.locked? %>
  <% if @pool.flex? %>
    <p class='flash notice'><b>Hinweis.</b> Team Abgabefrist abgelaufen. Team Bonustipps gesperrt.</p>
  <% else %>
    <p class='flash notice'><b>Hinweis.</b> Abgabefrist abgelaufen. Tippabgabe gesperrt.</p>
  <% end %>
<% end %>


  
  


<table class='bonus'>
  <tr class='bonus-round'>
    <td class='bonus-round-title'>Bonus Tipp - 1. Platz, 2. Platz</td>
  </tr>
  
<% if @pool.locked? %>
  
  <%= f.hidden_field :team1_id %>
  <%= f.hidden_field :team2_id %>

  <tr><td>
    <%= render_play_teams( @play ) %>
  </td></tr>
  
<% else %><!-- pool.locked? clause -->
<% if @pool.flex? %>
 <!-- NB: only needed for flex - in fixed winner gets calculated automatically -->

  <tr><td>
  <%= render_play_teams_for_form( @play, f ) %>
  </td></tr>

<% else %><!-- pool fix clause -->
  <%= f.hidden_field :team1_id %>
  <%= f.hidden_field :team2_id %>
<% end %><!-- pool.flex? -->
<% end %><!-- pool.locked? -->


  <tr><td>
  <%= render_event_quotes( @pool.event ) if @show_odds %>
  </td></tr>

</table>




<% if @pool.flex? %>
 
 <p>
  <% @pool.event.flex_rounds.each_with_index do |round,i| %>
    <% if i > 0 %>
      &bull;
    <% end %>
    <!-- todo: use prettified cleaned url
         add ready only attr to model      
      -->
    <%= link_to round.title, "##{round.id}" %>
  <% end %>
 </p>
 
  <%= render :partial => 'games_by_round',  :locals => { :rounds => @pool.event.flex_rounds, :user => @user, :pool => @pool, :f => f, :tabindex => 1000, :show_odds => @show_odds } %>
  <!-- todo: include group tables if groups exist -->
<% else %>
  <%= render :partial => 'games_by_group',  :locals => { :groups => @pool.event.groups, :user => @user, :pool => @pool, :f => f, :tabindex => 1000, :show_odds => @show_odds } %>
  <%= render :partial => 'games_by_round',  :locals => { :rounds => @pool.event.fix_playoff_rounds, :user => @user, :pool => @pool, :f => f, :tabindex => 2000, :show_odds => @show_odds } %>
<% end %>



<p>
  <%= f.submit t(:save_bets), :class => 'btn-primary' %>
  <%= link_to t(:back), play_path( @play ), :class => 'btn' %>
</p>  
<% end %>

<div id='debug' style='display: none;'></div>

app/views/plays/index.html.erb
<% title( 'Alle', @pool.full_title ) %>

<% content_for :breadcrumb do %>
 <%= link_to 'Wettpools', pools_path() %> ›
 <%= link_to @pool.full_title, pool_path(@pool) %> ›
 <%= link_to 'Alle Tipps', plays_path( :pool_id => @pool.id ) %>
<% end %>


<p>
  View: <%= link_to 'Tipps', plays_path( :pool_id => @pool.id )  %>
          ⋅
        <%= link_to 'Punkte', plays_path( :pool_id => @pool.id, :pts => 't', :tips => 'f' ) %>
          ⋅
        <%= link_to 'Tipps+Punkte', plays_path( :pool_id => @pool.id, :pts => 't' ) %>
        
</p>

<!-- todo:
   use current_play = nil or obj  instead of machmit  => lets us use play route for edit!!
  -->

<% machmit = (@pool.players.include?( current_user ) == false) %>

<table width='100%' cellspacing=0>
  <tr>
    <!-- left -->
    <td>
      <h1><%= @pool.full_title %> Tipps</h1>
    </td>
    <!-- right -->
    <td style='text-align: right;'>
<% if machmit %>
  <%= link_to 'Mach mit! Mittippen!', add_player_to_pool_path( @pool ), :class => 'btn-primary' %>
<% else %>
  <%= link_to 'Meine Tipps bearbeiten', edit_pool_player_path( @pool, current_user() ), :class => 'btn-primary' %>
<% end %>
    </td>
  </tr>
</table>


<table>
  <tr>
    <td><!-- user --></td>
    <td style='text-align: center;'>1. Platz</td>
    <td style='text-align: center;'>2. Platz</td>
    <% if @pool.team3? %><td style='text-align: center;'>3. Platz</td><% end %>
  </tr>
  <% @users.each do |user| %>
    <% play = Play.find_by_pool_id_and_user_id!( @pool.id, user.id ) %>
    <tr>
       <td>
         <span class='<%= hl_style_for_user(user) %>'>
           <%= link_to user.name, play_path(play.id) %>
         </span>
       </td>
       <%= render_play_team1( play ) %>
       <%= render_play_team2( play ) %>
       <%= render_play_team3( play ) if @pool.team3? %>
    </tr>
  <% end %><!-- users.each -->
</table>



<!-- table columns:
        1    => toto12x
        2    => team1
        3..n => tip 
       -3    => result
       -2    => team2
  last/-1    => date
  -->

<table class='plays' cellspacing=0>
<tr>
  <td colspan='2'></td>
  <% @users.each do |user| %>
   <td class='player-name'>
      <span class='<%= hl_style_for_user(user) %>'>
    <%= link_to pool_player_path( @pool, user ) do %>
       <%= raw( user.name.split(' ').join( '<br>' ) ) %>
    <% end %>
      </span>
   </td>
  <% end %><!-- users.each -->
</tr>


<% @rounds.each do |round| %>
<tr class='game-round'>
  <td colspan='2'></td>
  <td colspan='<%= 3+@users.count %>' class='game-round-title'><%= round.title %></td>
</tr>

  <% round.games.each do |game| %>
    <tr>
     
       <%= render_game_toto12x( game ) %>
       
       <%= render_game_team1( game ) %>
       
      <% @users.each do |user| %>
        <!-- NB: allow missing tip, that is, tip.nil? true !!! -->
        <% tip = Tip.find_by_user_id_and_pool_id_and_game_id( user.id, @pool.id, game.id ) %>
        
        <%= render_tip_score_v2( tip, :show_tips => @show_tips, :show_pts => @show_pts ) %>
      <% end %><!-- users.each --> 

       <%= render_game_score( game ) %>
       <%= render_game_team2( game ) %>
       <%= render_game_date( game ) %>
     </tr>
  <% end %> <!-- games.each -->
<% end %> <!-- rounds.each -->

<tr>
  <td colspan='2'></td>
  <% @users.each do |user| %>
   <td class='player-name'>
      <span class='<%= hl_style_for_user(user) %>'>
    <%= link_to pool_player_path( @pool, user ) do %>
       <%= raw( user.name.split(' ').join( '<br>' ) ) %>
    <% end %>
      </span>
   </td>
  <% end %><!-- users.each -->
</tr>

</table>

app/views/plays/show.html.erb
<% title( @user.name, @pool.full_title ) %>

<% content_for :breadcrumb do %>
 <%= link_to 'Wettpools', pools_path() %> ›
 <%= link_to @pool.full_title, pool_path(@pool) %> ›
 <%= link_to @user.name, play_path(@play) %>
<% end %>

<table width='100%' cellspacing=0>
  <tr>
    <!-- left -->
    <td>
      <h1><%= @user.name %> - <%=  @pool.full_title %> Tipps</h1>
    </td>
    <!-- right -->
    <td style='text-align: right;'>
      <% if current_user?( @user ) %> 
        <%= link_to t(:edit_bets), edit_play_path( @play ), :class => 'btn-primary' %>
      <% end %>
    </td>
  </tr>
</table>


  <%= render_play_teams( @play ) %>



<!-- table columns:
        1    => toto12x
        2    => bingo
        3    => team1
        4    => tip 
        5    => result
        6    => team2
        7    => date
  -->

<table class='play' cellspacing=0>
  
<% @rounds.each do |round|
      ranking = Point.find_by_user_id_and_pool_id_and_round_id( @user.id, @pool.id, round.id )
 %>
<tr class='game-round'>
  <td colspan='3'></td>
  <td colspan='4' class='game-round-title'><%= round.title %></td>
</tr>

  <% if @pool.flex? && round.calc? %>
     <tr>
       <td colspan='2'></td>
       <td colspan='4' class='game-no-fixtures'>Spielaufstellungen noch nicht bekannt.</td>
     </tr>
  <% else %>
   <% round.games.each do |game| 
         tip = Tip.find_by_user_and_pool_and_game( @user, @pool, game )
    %>
    <tr>
        
       <%= render_tip_toto12x( tip )  %>
       <%= render_tip_bingo( tip )  %>
       <%= render_game_team1( game ) %>
       <%= render_tip_score( tip )  %>
       <%= render_game_score( game ) %>
       <%= render_game_team2( game ) %>
       <%= render_game_date( game ) %>

     </tr>
  <% end %> <!-- games -->

  <tr><!-- todo: add style class -->
   <td></td>
    <td colspan='5'>
    <% if ranking.present? && ranking.total_pts > 0 %>
       <%= ranking.total_pts_str %> <%= ranking.total_pts %> Pkte

      <% if ranking.round_pts != ranking.total_pts && ranking.round_pts > 0 %>
        (+ <%= ranking.round_pts_str %> <%= ranking.round_pts %> Pkte)
      <% end %>
    <% end %>
  </td>
  </tr>
  
  <% end %> <!-- if pool.flex? && round.calc? -->
<% end %> <!-- rounds -->

</table>



<!-- add scoring/ranking block/data -->
<table>
  <tr>
    <td>
    <td colspan='3'>Runde</td>
    <td></td>
    <td colspan='3'>Gesamt</td>
  </tr>
<% @play.complete_rankings.each do |ranking| %>
 <tr>
  <td>(<%= ranking.round.pos %>) <%= ranking.round.title %></td>
  <td><%= ranking.round_pts %> Pkte</td>
  <td>=></td>
  <td>#<%= ranking.round_pos %></td>
  <td>/</td>
  <td><%= ranking.total_pts %> Pkte</td>
  <td>=></td>
  <td>#<%= ranking.total_pos %> <%= ranking.diff_total_pos_str %></td>
 </tr>
<% end %>
</table>